const DATA_URL='./data/prospects.json';
const STORAGE={settings:'sj-prospecting-settings-v1',progress:'sj-prospecting-progress-v1',activity:'sj-prospecting-activity-v1',prospects:'sj-prospecting-custom-prospects-v1'};
const DEFAULT_SETTINGS={senderName:'Anastaysia',price:100,deliveryMinutes:60,paymentLabel:'PayPal invoice',paymentUrl:'https://www.paypal.com/invoice/p/#7T6DC9A6WFH3XXCT',followUpHours:3.5};
const STATUS_LABELS={new:'Not contacted',sent:'Sent',replied:'Replied',interested:'Interested',paid:'Paid','not-now':'Not now',dnc:'Do not contact'};
const BRANCH_LABELS={interested:'Interested / wants to proceed',price:'Asks about price',proof:'Asks for proof or portfolio',revision:'Requests a change',followup:'No response — one follow-up',notnow:'Not now',dnc:'Do not contact'};
const state={leads:[],settings:loadJSON(STORAGE.settings,DEFAULT_SETTINGS),progress:loadJSON(STORAGE.progress,{}),activity:loadJSON(STORAGE.activity,[]),activeLeadId:null,activeBranch:'interested',view:'queue',installPrompt:null};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=n=>`<svg aria-hidden="true"><use href="#i-${n}"/></svg>`;
function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}}
function saveState(){localStorage.setItem(STORAGE.settings,JSON.stringify(state.settings));localStorage.setItem(STORAGE.progress,JSON.stringify(state.progress));localStorage.setItem(STORAGE.activity,JSON.stringify(state.activity.slice(0,500)));$('#syncLabel').textContent=`Saved on this device · ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`}
function normalizeLead(r,i){return{id:String(r.ID||r.id||`IMPORTED-${i+1}`),rank:Number(r.Rank||r.rank||i+1),business:String(r.Business||r.business||'Unnamed business'),industry:String(r.Industry||r.industry||'Other'),area:String(r['City / Area']||r.area||'San Jose, CA'),email:String(r['Public Email']||r.email||''),website:String(r.Website||r.website||''),source:String(r['Verification Source URL']||r.source||r.Website||''),evidence:String(r['Personalization Evidence']||r.evidence||''),concept:String(r['Sample Concept']||r.concept||''),reason:String(r['Why Selected']||r.reason||''),score:Number(r['Priority Score']||r['Response Score']||r.score||0),forecast:String(r['Forecast Reply Window']||r.forecast||'Unknown'),predictedReply:String(r['Predicted First Reply']||r.predictedReply||''),verificationTier:String(r['Verification Tier']||r.verificationTier||''),verificationDate:String(r['Verification Date']||r.verificationDate||''),subject:String(r.Subject||r.subject||`Private content preview for ${r.Business||r.business||'your business'}`),graphic:String(r['Graphic Path']||r.graphic||(r['Graphic Filename']?`graphics/${r['Graphic Filename']}`:'')),raw:r}}
function progressFor(id){return state.progress[id]||{status:'new'}}function statusFor(id){return progressFor(id).status||'new'}function formatStatus(s){return STATUS_LABELS[s]||s}
function timestampLabel(iso){if(!iso)return'';const d=new Date(iso),m=Math.floor((Date.now()-d)/60000);if(m<1)return'just now';if(m<60)return`${m}m ago`;const h=Math.floor(m/60);return h<24?`${h}h ago`:d.toLocaleDateString([],{month:'short',day:'numeric'})}
function dueLabel(iso){if(!iso)return'';const m=Math.ceil((new Date(iso)-Date.now())/60000);if(m<=0)return'Due now';return m<60?`Due in ${m}m`:`Due in ${(m/60).toFixed(m%60?1:0)}h`}
function paymentSentence(){const{paymentLabel,paymentUrl}=state.settings;return`Payment is available by ${paymentLabel}${paymentUrl?`: ${paymentUrl}`:''}.`}
function initialMessage(l){const s=state.settings,e=l.evidence?`I reviewed your public website and noticed that ${l.evidence}.`:'I reviewed your public website and prepared a customer-ready idea for your business.',c=l.concept?`\n\nHere is one concept I drafted:\n\n“${l.concept}”`:'';return`Hi ${l.business} team,\n\n${e}${c}\n\nI create same-day custom content packs for local service businesses: 10 ready-to-post Google/Facebook captions, review responses, customer follow-up messages, stronger calls-to-action and one finished promotional graphic. The complete package is $${s.price} flat, with no contract or recurring charge.\n\nI attached a private preview created for ${l.business}. If you want the complete pack today, reply “YES.” ${paymentSentence()} Delivery is within ${s.deliveryMinutes} minutes of confirmation.\n\nThank you,\n${s.senderName}`}
function replyMessage(l,b){const s=state.settings,m={interested:`Thanks for the quick reply. I’ll customize the complete pack for ${l.business}: 10 ready-to-post captions, review responses, follow-up messages, stronger calls-to-action and the finished promotional graphic. The total is $${s.price} flat. ${paymentSentence()} Once confirmed, I’ll deliver within ${s.deliveryMinutes} minutes.`,price:`Yes—the complete package is $${s.price} total, not a subscription. It includes 10 ready-to-post captions, review-response templates, customer follow-up messages, stronger calls-to-action and one finished promotional graphic customized for ${l.business}. If you want to proceed, reply “YES” and I’ll send the payment step.`,proof:`The attached ${l.business} preview is the exact quality reference I can truthfully provide right now. I don’t want to invent client results or performance claims. If helpful, I can also send two additional text samples tailored to your services before you decide.`,revision:`Absolutely. Tell me the service, tone or wording you want changed, and I’ll revise the private ${l.business} preview once at no charge. If the revised direction works, the complete same-day pack remains $${s.price} flat.`,followup:`Hi ${l.business} team—one quick follow-up on the private preview I sent earlier. I can still complete the full custom content pack today for $${s.price} flat. If you want it, reply “YES.” If not, no response is needed and I won’t send another follow-up.\n\nThank you,\n${s.senderName}`,notnow:`Understood—thanks for letting me know. I won’t keep following up. If the timing changes, reply to this email and I can still create a fresh ${l.business} package.`,dnc:`Understood. I’ve marked ${l.business} as do not contact and will not send further outreach.`};return m[b]||m.interested}
function chatPrompt(l){const s=state.settings;return`Prospect workspace ${l.id}: ${l.business} (${l.industry}, ${l.area}). Verified public email: ${l.email}. Source: ${l.source}. Offer: one-time $${s.price} same-day content pack with 10 posts, review responses, follow-up messages, calls-to-action and one finished graphic; delivery within ${s.deliveryMinutes} minutes after payment by ${s.paymentLabel}${s.paymentUrl?` at ${s.paymentUrl}`:''}. Manage only this prospect’s email conversation and retain its history under code ${l.id}. Draft concise, truthful email replies in ${s.senderName}’s voice. Never invent clients, results, testimonials, urgency or portfolio claims. Use the existing preview as proof. Respect any do-not-contact request immediately and recommend no further outreach. If the prospect is interested, close clearly on scope, $${s.price} price and delivery timing. If they ask for proof, offer the preview and two additional text samples. Initial evidence: ${l.evidence||'public website reviewed'}. Predicted response: ${l.predictedReply||'May ask about price or timing, or may not reply.'}`}
function getDueLeads(){return state.leads.filter(l=>{const p=progressFor(l.id);return p.status==='sent'&&p.followUpAt&&new Date(p.followUpAt)<=Date.now()}).sort((a,b)=>new Date(progressFor(a.id).followUpAt)-new Date(progressFor(b.id).followUpAt))}
function getNextLead(){const d=getDueLeads();if(d.length)return{lead:d[0],mode:'followup'};const l=[...state.leads].sort((a,b)=>a.rank-b.rank).find(x=>statusFor(x.id)==='new');return l?{lead:l,mode:'initial'}:null}
function metricHTML(l,v,a=false){return`<div class="metric${a?' accent':''}"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`}
function computeCounts(){const c=Object.fromEntries(Object.keys(STATUS_LABELS).map(k=>[k,0]));state.leads.forEach(l=>c[statusFor(l.id)]=(c[statusFor(l.id)]||0)+1);return c}
function renderMetrics(){const c=computeCounts(),d=getDueLeads().length;$('#metrics').innerHTML=metricHTML('Not contacted',c.new,c.new>0)+metricHTML('Follow-ups due',d,d>0)+metricHTML('Replies',c.replied+c.interested+c.paid)+metricHTML('Paid',c.paid);$('#activityMetrics').innerHTML=metricHTML('Sent',c.sent+c.replied+c.interested+c.paid+c['not-now']+c.dnc)+metricHTML('Interested',c.interested)+metricHTML('Paid',c.paid,c.paid>0)}
function leadImage(l,cl=''){return l.graphic?`<img class="${cl}" src="./${esc(l.graphic)}" alt="Private promotional preview for ${esc(l.business)}" loading="lazy">`:`<div class="${cl} empty-state">No graphic imported</div>`}
function renderNextLead(){const n=getNextLead(),p=$('#nextLeadPanel');if(!n){p.innerHTML='<div class="panel-empty"><div><h2>Queue complete</h2><p>Every lead has a recorded status. Review replies or import a new list.</p></div></div>';return}const{lead:l,mode}=n,pr=progressFor(l.id),f=mode==='followup';p.innerHTML=`<div class="next-inner"><div class="next-copy"><div class="lead-kicker"><span class="rank-pill">${f?'FOLLOW-UP DUE':`RANK #${l.rank}`}</span><span class="score-pill">${l.score}/100</span><span class="status ${esc(pr.status||'new')}">${esc(formatStatus(pr.status||'new'))}</span></div><h2>${esc(l.business)}</h2><p class="lead-email">${esc(l.email)}</p><p class="lead-reason">${esc(f?`The first message was sent ${timestampLabel(pr.sentAt)}. Send the single approved follow-up now.`:l.reason)}</p><div class="micro-row"><span>${icon('clock')}${esc(f?dueLabel(pr.followUpAt):l.forecast)}</span><span>${esc(l.industry)}</span><span>${esc(l.area)}</span></div><div class="action-row"><button class="primary-button" data-open-lead="${esc(l.id)}" data-branch="${f?'followup':'initial'}" type="button">${icon(f?'clock':'send')}${f?'Prepare follow-up':'Prepare email + graphic'}</button><button class="secondary-button" data-skip-lead="${esc(l.id)}" type="button">Skip for now</button></div></div><div class="preview-frame">${leadImage(l)}</div></div>`}
function queueCard(l){const p=progressFor(l.id);return`<article class="queue-card"><div class="rank-square">#${l.rank}</div><div><h3>${esc(l.business)}</h3><p>${esc(l.email)} · Sent ${timestampLabel(p.sentAt)}</p></div><button class="secondary-button" data-open-lead="${esc(l.id)}" data-branch="followup" type="button">Prepare</button></article>`}
function renderDue(){const d=getDueLeads();$('#dueCount').textContent=d.length;$('#dueList').innerHTML=d.length?d.slice(0,8).map(queueCard).join(''):'<div class="empty-state">No follow-ups are due right now.</div>'}
function filteredLeads(){const q=$('#leadSearch').value.trim().toLowerCase(),s=$('#statusFilter').value,i=$('#industryFilter').value,o=$('#sortFilter').value,l=state.leads.filter(x=>(!q||`${x.business} ${x.email} ${x.industry} ${x.area} ${x.id}`.toLowerCase().includes(q))&&(s==='all'||statusFor(x.id)===s)&&(i==='all'||x.industry===i));l.sort((a,b)=>o==='business'?a.business.localeCompare(b.business):o==='score'?b.score-a.score||a.rank-b.rank:o==='due'?(progressFor(a.id).followUpAt?new Date(progressFor(a.id).followUpAt):Infinity)-(progressFor(b.id).followUpAt?new Date(progressFor(b.id).followUpAt):Infinity)||a.rank-b.rank:a.rank-b.rank);return l}
function leadCard(l){const s=statusFor(l.id),p=progressFor(l.id),x=s==='sent'&&p.followUpAt?dueLabel(p.followUpAt):l.forecast;return`<article class="lead-card" data-open-lead="${esc(l.id)}" tabindex="0" role="button" aria-label="Open ${esc(l.business)}"><div class="rank-square">#${l.rank}</div><div><h3>${esc(l.business)}</h3><p>${esc(l.email)} · ${esc(l.industry)}</p></div><div class="card-tail"><span class="status ${esc(s)}">${esc(formatStatus(s))}</span><small class="muted">${esc(x)}</small></div></article>`}
function renderLeads(){const l=filteredLeads();$('#resultsCount').textContent=`${l.length} lead${l.length===1?'':'s'}`;$('#leadList').innerHTML=l.length?l.map(leadCard).join(''):'<div class="empty-state">No leads match these filters.</div>'}
function activityHTML(a){return a.length?a.map(x=>`<article class="timeline-item"><span class="timeline-dot"></span><div><h3>${esc(x.business||x.leadId||'Workspace')}</h3><p>${esc(x.action)}</p></div><time datetime="${esc(x.at)}">${esc(timestampLabel(x.at))}</time></article>`).join(''):'<div class="empty-state">Actions you take in the app will appear here.</div>'}
function renderActivity(){const a=[...state.activity].sort((x,y)=>new Date(y.at)-new Date(x.at));$('#recentActivity').innerHTML=activityHTML(a.slice(0,4));$('#activityList').innerHTML=activityHTML(a)}
function renderSettings(){const f=$('#settingsForm');Object.entries(state.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v})}
function renderAll(){renderMetrics();renderNextLead();renderDue();renderLeads();renderActivity();renderSettings()}
function addActivity(l,a){state.activity.unshift({leadId:l?.id||null,business:l?.business||'Workspace',action:a,at:new Date().toISOString()});state.activity=state.activity.slice(0,500);saveState()}
function setLeadStatus(l,s){const n=new Date(),e=progressFor(l.id),u={...e,status:s,updatedAt:n.toISOString()};if(s==='sent'){u.sentAt=e.sentAt||n.toISOString();u.followUpAt=new Date(n.getTime()+Number(state.settings.followUpHours)*3600000).toISOString()}if(['replied','interested','paid','not-now','dnc'].includes(s))u.followUpAt=null;state.progress[l.id]=u;addActivity(l,`Marked ${formatStatus(s).toLowerCase()}`);renderAll();if(state.activeLeadId===l.id)openLead(l.id,state.activeBranch,false);toast(`${l.business}: ${formatStatus(s)}`)}
const subjectForReply=l=>l.subject.toLowerCase().startsWith('re:')?l.subject:`Re: ${l.subject}`;
function openLead(id,b='initial',log=true){const l=state.leads.find(x=>x.id===id);if(!l)return;state.activeLeadId=id;state.activeBranch=b==='initial'?'interested':b;const s=statusFor(id),init=b==='initial',sub=init?l.subject:subjectForReply(l),msg=init?initialMessage(l):replyMessage(l,b);$('#leadSheet').innerHTML=`<div class="sheet-head"><div><div class="lead-kicker"><span class="rank-pill">RANK #${l.rank}</span><span class="score-pill">${l.score}/100</span><span class="status ${esc(s)}">${esc(formatStatus(s))}</span></div><h2>${esc(l.business)}</h2><p>${esc(l.email)}</p></div><button class="icon-button" data-close-sheet type="button" aria-label="Close lead"><svg><use href="#i-close"/></svg></button></div>${leadImage(l,'sheet-preview')}<div class="sheet-tabs"><button class="active" data-tab="outreach" type="button">Outreach</button><button data-tab="replies" type="button">Replies</button><button data-tab="evidence" type="button">Evidence</button></div>
<section class="tab-panel active" data-panel="outreach"><div class="message-block"><label for="sheetSubject">Subject</label><input id="sheetSubject" value="${esc(sub)}"></div><div class="message-block"><label for="sheetMessage">${init?'Personalized initial email':'Prepared reply'}</label><textarea id="sheetMessage">${esc(msg)}</textarea></div><div class="sheet-actions"><button class="primary-button" data-share-lead type="button">${icon('send')}Share email + graphic</button><button class="secondary-button" data-open-email type="button">${icon('external')}Open email app</button><button class="secondary-button" data-copy-message type="button">${icon('copy')}Copy email</button><button class="secondary-button" data-download-graphic type="button">${icon('download')}Download graphic</button><button class="secondary-button" data-open-chat type="button">${icon('chat')}Open ChatGPT workspace</button><button class="secondary-button" data-copy-chat type="button">${icon('copy')}Copy ChatGPT prompt</button></div><div><p class="eyebrow">RECORD OUTCOME</p><div class="status-actions">${Object.entries(STATUS_LABELS).map(([k,v])=>`<button class="${k===s?'active':''}" data-set-status="${k}" type="button">${esc(v)}</button>`).join('')}</div></div></section>
<section class="tab-panel" data-panel="replies"><div class="message-block"><label for="branchSelect">What did they say?</label><select class="branch-select" id="branchSelect">${Object.entries(BRANCH_LABELS).map(([k,v])=>`<option value="${k}" ${k===state.activeBranch?'selected':''}>${esc(v)}</option>`).join('')}</select></div><div class="message-block"><label for="replyMessage">Prepared truthful reply</label><textarea id="replyMessage">${esc(replyMessage(l,state.activeBranch))}</textarea></div><div class="sheet-actions"><button class="primary-button" data-open-reply type="button">${icon('external')}Open reply in email app</button><button class="secondary-button" data-copy-reply type="button">${icon('copy')}Copy reply</button></div></section>
<section class="tab-panel" data-panel="evidence"><div class="evidence-card"><h3>Why this lead</h3><p>${esc(l.reason)}</p></div><div class="evidence-card"><h3>Personalization evidence</h3><p>${esc(l.evidence||'No evidence note was imported.')}</p></div><div class="evidence-card"><h3>Predicted response</h3><p>${esc(l.predictedReply||'No forecast note was imported.')}</p></div><div class="evidence-card"><h3>Verification</h3><p>${esc(l.verificationTier||'Public source')} · ${esc(l.verificationDate||'Date not recorded')}</p></div><a class="source-link" href="${esc(l.source)}" target="_blank" rel="noopener noreferrer">${icon('external')}Open verification source</a></section>`;$('#sheetBackdrop').hidden=false;$('#leadSheet').setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('#leadSheet').classList.add('open'));document.body.style.overflow='hidden';if(log)addActivity(l,init?'Opened initial outreach workspace':`Prepared ${BRANCH_LABELS[b]||'reply'} message`)}
function closeSheet(){$('#leadSheet').classList.remove('open');$('#leadSheet').setAttribute('aria-hidden','true');document.body.style.overflow='';setTimeout(()=>{$('#sheetBackdrop').hidden=true},220)}
const activeLead=()=>state.leads.find(x=>x.id===state.activeLeadId);
function currentDraft(reply=false){const l=activeLead();return reply?{lead:l,subject:subjectForReply(l),message:$('#replyMessage')?.value||replyMessage(l,state.activeBranch)}:{lead:l,subject:$('#sheetSubject')?.value||l.subject,message:$('#sheetMessage')?.value||initialMessage(l)}}
const mailtoUrl=(l,s,m)=>`mailto:${encodeURIComponent(l.email)}?subject=${encodeURIComponent(s)}&body=${encodeURIComponent(m)}`;
async function copyText(v,msg='Copied'){try{await navigator.clipboard.writeText(v)}catch{const a=document.createElement('textarea');a.value=v;a.style.position='fixed';a.style.opacity='0';document.body.append(a);a.select();document.execCommand('copy');a.remove()}toast(msg)}
async function graphicFile(l){if(!l.graphic)return null;const r=await fetch(`./${l.graphic}`);if(!r.ok)throw new Error('Graphic could not be loaded');const b=await r.blob(),n=l.graphic.split('/').pop()||`${l.id}-preview.png`;return new File([b],n,{type:b.type||'image/png'})}
async function shareLead(){const{lead:l,subject:s,message:m}=currentDraft();try{const f=await graphicFile(l);if(navigator.share&&f&&(!navigator.canShare||navigator.canShare({files:[f]}))){await navigator.share({title:s,text:m,files:[f]});addActivity(l,'Shared draft and graphic to Android share sheet');toast('Shared—mark Sent after you finish sending');return}if(navigator.share){await navigator.share({title:s,text:m});if(f)downloadFile(f,f.name);addActivity(l,'Shared draft; downloaded graphic separately');toast('Draft shared; graphic downloaded separately');return}if(f)downloadFile(f,f.name);await copyText(m,'Email copied; graphic downloaded');window.location.href=mailtoUrl(l,s,m)}catch(e){if(e?.name!=='AbortError')toast(e?.message||'Sharing failed')}}
function downloadFile(b,n){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
async function downloadGraphic(){const l=activeLead();try{const f=await graphicFile(l);if(!f)throw new Error('No graphic is available');downloadFile(f,f.name);addActivity(l,'Downloaded matching preview graphic');toast('Graphic downloaded')}catch(e){toast(e.message)}}
function openChat(){const l=activeLead(),u=`https://chatgpt.com/?q=${encodeURIComponent(chatPrompt(l))}`;addActivity(l,'Opened prospect-specific ChatGPT workspace');window.open(u,'_blank','noopener,noreferrer')}
function navigate(v){state.view=v;$$('.view').forEach(e=>e.classList.toggle('active',e.dataset.view===v));$$('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===v));window.scrollTo({top:0,behavior:'smooth'})}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2600)}
function csvCell(v){return`"${String(v??'').replaceAll('"','""')}"`}function downloadJSON(v,n){downloadFile(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}),n)}
function exportCsv(){const h=['ID','Rank','Business','Industry','Email','Status','Sent At','Follow-Up At','Updated At','Source'],r=state.leads.map(l=>{const p=progressFor(l.id);return[l.id,l.rank,l.business,l.industry,l.email,p.status||'new',p.sentAt||'',p.followUpAt||'',p.updatedAt||'',l.source]}),c=[h,...r].map(x=>x.map(csvCell).join(',')).join('\n');downloadFile(new Blob([c],{type:'text/csv;charset=utf-8'}),`sj-prospecting-progress-${new Date().toISOString().slice(0,10)}.csv`);addActivity(null,'Exported progress CSV')}
const importJSONFile=async f=>JSON.parse(await f.text());
function populateIndustries(){const s=$('#industryFilter'),c=s.value||'all';s.innerHTML='<option value="all">All categories</option>'+[...new Set(state.leads.map(l=>l.industry))].sort().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');s.value=[...s.options].some(o=>o.value===c)?c:'all'}
function bindEvents(){document.addEventListener('click',async e=>{const n=e.target.closest('[data-nav]');if(n)navigate(n.dataset.nav);const o=e.target.closest('[data-open-lead]');if(o)openLead(o.dataset.openLead,o.dataset.branch||'initial');if(e.target.closest('[data-close-sheet]')||e.target===$('#sheetBackdrop'))closeSheet();const t=e.target.closest('[data-tab]');if(t){$$('.sheet-tabs button',$('#leadSheet')).forEach(x=>x.classList.toggle('active',x===t));$$('.tab-panel',$('#leadSheet')).forEach(x=>x.classList.toggle('active',x.dataset.panel===t.dataset.tab))}const s=e.target.closest('[data-set-status]');if(s)setLeadStatus(activeLead(),s.dataset.setStatus);if(e.target.closest('[data-share-lead]'))await shareLead();if(e.target.closest('[data-copy-message]')){const d=currentDraft();await copyText(`Subject: ${d.subject}\n\n${d.message}`,'Email copied');addActivity(d.lead,'Copied initial email')}if(e.target.closest('[data-open-email]')){const d=currentDraft();addActivity(d.lead,'Opened draft in email app');window.location.href=mailtoUrl(d.lead,d.subject,d.message)}if(e.target.closest('[data-download-graphic]'))await downloadGraphic();if(e.target.closest('[data-open-chat]'))openChat();if(e.target.closest('[data-copy-chat]')){const l=activeLead();await copyText(chatPrompt(l),'ChatGPT prompt copied');addActivity(l,'Copied ChatGPT workspace prompt')}if(e.target.closest('[data-copy-reply]')){const d=currentDraft(true);await copyText(d.message,'Reply copied');addActivity(d.lead,`Copied ${BRANCH_LABELS[state.activeBranch]} reply`)}if(e.target.closest('[data-open-reply]')){const d=currentDraft(true);addActivity(d.lead,`Opened ${BRANCH_LABELS[state.activeBranch]} reply`);window.location.href=mailtoUrl(d.lead,d.subject,d.message)}const k=e.target.closest('[data-skip-lead]');if(k)setLeadStatus(state.leads.find(x=>x.id===k.dataset.skipLead),'not-now')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#leadSheet').classList.contains('open'))closeSheet();if((e.key==='Enter'||e.key===' ')&&e.target.matches('.lead-card')){e.preventDefault();openLead(e.target.dataset.openLead)}});$('#leadSheet').addEventListener('change',e=>{if(e.target.id==='branchSelect'){state.activeBranch=e.target.value;$('#replyMessage').value=replyMessage(activeLead(),state.activeBranch)}});['leadSearch','statusFilter','industryFilter','sortFilter'].forEach(id=>$(`#${id}`).addEventListener(id==='leadSearch'?'input':'change',renderLeads));$('#resetFilters').addEventListener('click',()=>{$('#leadSearch').value='';$('#statusFilter').value='all';$('#industryFilter').value='all';$('#sortFilter').value='rank';renderLeads()});$('#filterToggle').addEventListener('click',()=>$('#filters').classList.toggle('open'));$('#menuButton').addEventListener('click',()=>navigate('settings'));
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);state.settings={senderName:String(d.get('senderName')).trim(),price:Number(d.get('price')),deliveryMinutes:Number(d.get('deliveryMinutes')),paymentLabel:String(d.get('paymentLabel')).trim(),paymentUrl:String(d.get('paymentUrl')).trim(),followUpHours:Number(d.get('followUpHours'))};addActivity(null,'Updated outreach settings');renderAll();toast('Settings saved')});
$('#exportBackup').addEventListener('click',()=>{downloadJSON({version:1,exportedAt:new Date().toISOString(),settings:state.settings,progress:state.progress,activity:state.activity,prospects:state.leads.map(l=>l.raw)},`sj-prospecting-backup-${new Date().toISOString().slice(0,10)}.json`);addActivity(null,'Exported full workspace backup')});$('#exportCsv').addEventListener('click',exportCsv);
$('#importBackup').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const d=await importJSONFile(f);if(!d||typeof d!=='object'||!d.progress)throw new Error('This is not a valid workspace backup.');state.settings={...DEFAULT_SETTINGS,...d.settings};state.progress=d.progress||{};state.activity=d.activity||[];if(Array.isArray(d.prospects)&&d.prospects.length){localStorage.setItem(STORAGE.prospects,JSON.stringify(d.prospects));state.leads=d.prospects.map(normalizeLead)}addActivity(null,'Imported workspace backup');populateIndustries();renderAll();toast('Backup imported')}catch(x){toast(x.message||'Backup import failed')}e.target.value=''});
$('#importProspects').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const d=await importJSONFile(f);if(!Array.isArray(d)||!d.length)throw new Error('Prospects JSON must be a non-empty array.');const n=d.map(normalizeLead);if(new Set(n.map(l=>l.id)).size!==n.length)throw new Error('Every prospect must have a unique ID.');if(n.some(l=>!l.email.includes('@')))throw new Error('Every prospect needs a valid email address.');localStorage.setItem(STORAGE.prospects,JSON.stringify(d));state.leads=n;addActivity(null,`Imported ${n.length} prospects`);populateIndustries();renderAll();toast(`${n.length} prospects imported`)}catch(x){toast(x.message||'Prospect import failed')}e.target.value=''});
$('#clearActivity').addEventListener('click',()=>{if(confirm('Clear the activity log? Lead statuses will remain.')){state.activity=[];saveState();renderActivity()}});$('#resetWorkspace').addEventListener('click',()=>{if(!confirm('Reset all statuses, activity, settings, and imported prospect data on this device? Export a backup first if needed.'))return;Object.values(STORAGE).forEach(k=>localStorage.removeItem(k));state.settings=structuredClone(DEFAULT_SETTINGS);state.progress={};state.activity=[];location.reload()});$('#installButton').addEventListener('click',async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installButton').hidden=true})}
async function init(){$('#todayLabel').textContent=new Date().toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'});try{const c=loadJSON(STORAGE.prospects,null),r=Array.isArray(c)&&c.length?c:await fetch(DATA_URL).then(x=>{if(!x.ok)throw new Error('Lead data failed to load');return x.json()});state.leads=r.map(normalizeLead).sort((a,b)=>a.rank-b.rank);populateIndustries();bindEvents();renderAll();$('#syncLabel').textContent=`${state.leads.length} leads · saved on device`}catch(e){$('#nextLeadPanel').innerHTML=`<div class="panel-empty"><div><h2>Could not load prospects</h2><p>${esc(e.message)}</p></div></div>`}if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});setInterval(()=>{renderMetrics();renderNextLead();renderDue()},60000)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('#installButton').hidden=false});window.addEventListener('appinstalled',()=>{state.installPrompt=null;$('#installButton').hidden=true;toast('App installed')});init();
